### ISSUE TITLE
Where are Matlab data files?

### ISSUE THREAD

**Issue by usptact** [sdrogers/fcmlcode#1]
Most of the Matlab scripts don't run because the respective "load" does not find the MAT file with data.

For example "matlab/chapter4/logmh.m", the following line ends up with error if the script is run from the same directory:
`load ../data/logregdata;`

Thanks

**Comment by sdrogers** [comment]
Sorry for the enormous delay - hadn't been checking this. I will dig them out

**Comment by usptact** [comment]
Thank you very much! I am still interested!

**Comment by smvazirizade** [comment]
Hi
The new scripts that I have submitted to Simon don't have this issue.
Thanks
https://github.com/smvazirizade/fcmlcode/tree/master/matlab

**Comment by sdrogers** [comment]
Hi Mohsen,
Thanks!!
I’ve merged your pull request…
Simon

--
Simon Rogers
simon.d.rogers@gmail.com
