### ISSUE TITLE
Missing file: synthdata.mat

### ISSUE THREAD

**Issue by oaansari** [sdrogers/fcmlcode#4]
Hi, 
It might be slightly an unrelated question. I hope someone can answer this. 
Exercise 1.9 in Chapter 1 requires a file named "synthdata.mat". I could not find the file on this repository. Would you please let me know if it will be uploaded to this repository?

Thanks,

**Comment by zz4fap** [comment]
The file named "synthdata.mat" is still missing. Could you help me find it, please?
